version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: inkr_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./backend:/var/www/html
    networks:
      - inkr_network

  webserver:
    image: nginx:alpine
    container_name: inkr_webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html
      - ./backend/nginx:/etc/nginx/conf.d
    networks:
      - inkr_network

  db:
    image: mysql:8
    container_name: inkr_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inkr_db
      MYSQL_USER: inkr_user
      MYSQL_PASSWORD: inkr_pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - inkr_network

networks:
  inkr_network:
    driver: bridge

volumes:
  db_data:
